<a href="https://colab.research.google.com/github/AanchalDogra/CNN/blob/main/Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: import numpy and pandas , create one list and one numpy array

import numpy as np
import pandas as pd

# Create a list
my_list = [1, 2, 3, 4, 5]

# Create a numpy array
my_array = np.array(my_list)


In [ ]:
my_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
my_array*2

array([ 2,  4,  6,  8, 10])

In [ ]:
my_array.shape

(5,)

In [ ]:
np.arange(1,5)

array([1, 2, 3, 4])

In [ ]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [ ]:
 import numpy as np

# Create a 3x4 matrix of random integers
matrix = np.random.randint(0, 100, size=(3, 4))

In [ ]:
matrix[matrix > 5]

array([83, 18, 25, 44, 51, 93, 89, 54, 54, 59])

In [ ]:
matrix[matrix % 2 == 0]

array([18,  0, 44, 54, 54])

In [ ]:
matrix2 = matrix.reshape(4,3)

In [ ]:
matrix2

array([[83, 18,  0],
       [25, 44, 51],
       [ 1, 93, 89],
       [54, 54, 59]])

In [ ]:
matrix@matrix2

array([[ 8689,  3636,  2393],
       [ 9950,  8151,  8177],
       [11977, 12186, 11041]])

In [ ]:
np.matmul(matrix,matrix2)

array([[ 8689,  3636,  2393],
       [ 9950,  8151,  8177],
       [11977, 12186, 11041]])

In [ ]:
test = np.dot(matrix,matrix2)

In [ ]:
matrix.flatten()

array([83, 18,  0, 25, 44, 51,  1, 93, 89, 54, 54, 59])

In [ ]:
matrix.ravel()

array([83, 18,  0, 25, 44, 51,  1, 93, 89, 54, 54, 59])

In [ ]:
B = np.arange(24).reshape(2,3,4)
B1 = np.arange(24).reshape(2,12)


In [ ]:
B1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [ ]:
B

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [ ]:
np.random.rand(10)*50

array([18.95658197, 10.31337318, 30.45638134, 15.2356914 , 11.09300231,
       29.83648667,  9.11889293,  5.70538566,  6.73766849,  8.36727471])

In [ ]:
np.random.rand(10)

array([0.93139124, 0.82178151, 0.53463355, 0.82994521, 0.28670568,
       0.38834636, 0.39873008, 0.14283055, 0.06692123, 0.43673589])

In [ ]:
# generate 10 float random numbers in the rangen[50,75]

In [ ]:
50 + np.random.rand(10)*25

array([71.19981568, 63.52588977, 56.83649368, 56.88221915, 68.97432938,
       53.7693199 , 53.58741797, 50.79577491, 67.38290691, 59.75001148])