<a href="https://colab.research.google.com/github/AanchalDogra/CNN/blob/main/Numpy_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# prompt: import numpy and pandas , create one list and one numpy array

import numpy as np
import pandas as pd

# Create a list
my_list = [1, 2, 3, 4, 5]

# Create a numpy array
my_array = np.array(my_list)


In [3]:
my_list*2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [4]:
my_array*2

array([ 2,  4,  6,  8, 10])

In [5]:
my_array.shape

(5,)

In [6]:
np.arange(1,5)

array([1, 2, 3, 4])

In [7]:
np.arange(1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [8]:
 import numpy as np

# Create a 3x4 matrix of random integers
matrix = np.random.randint(0, 100, size=(3, 4))

In [9]:
matrix[matrix > 5]

array([83, 18, 25, 44, 51, 93, 89, 54, 54, 59])

In [10]:
matrix[matrix % 2 == 0]

array([18,  0, 44, 54, 54])

In [11]:
matrix2 = matrix.reshape(4,3)

In [12]:
matrix2

array([[83, 18,  0],
       [25, 44, 51],
       [ 1, 93, 89],
       [54, 54, 59]])

In [13]:
matrix@matrix2

array([[ 8689,  3636,  2393],
       [ 9950,  8151,  8177],
       [11977, 12186, 11041]])

In [14]:
np.matmul(matrix,matrix2)

array([[ 8689,  3636,  2393],
       [ 9950,  8151,  8177],
       [11977, 12186, 11041]])

In [15]:
test = np.dot(matrix,matrix2)

In [16]:
matrix.flatten()

array([83, 18,  0, 25, 44, 51,  1, 93, 89, 54, 54, 59])

In [17]:
matrix.ravel()

array([83, 18,  0, 25, 44, 51,  1, 93, 89, 54, 54, 59])